### ISSUE TITLE
Mobile view

### ISSUE THREAD

**Issue by AutistaXR** [AbnerP/PReC-website#131]
When visiting the site through a phone, many elements on the screen get cut or misaligned.

**Comment by AbnerP** [comment]
Is the issue in the driver's screen?

**Comment by AutistaXR** [comment]
That appears to be the case. I attach a screenshot. 
![Screenshot_20220102-105200_Samsung Internet](https://user-images.githubusercontent.com/96986412/147886215-8b6b1270-c8f6-4c99-a3df-8fd686e6e5e8.jpg)

**Comment by AbnerP** [comment]
I see, I'll work on it soon.
